### ISSUE TITLE
Get requirements

### ISSUE THREAD

**Issue by Wongprayoon** [codnguy/octo#1]
# TODO

- [ ] Gathering customer requirements
- [x] Research existing solutions
- [ ] Define market needs
- [ ] Generate specifications
